# Generated by Django 3.2.7 on 2022-01-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя и фамилия куратора')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='curators', verbose_name='Фотография')),
                ('is_main', models.BooleanField(default=False, verbose_name='На главной странице')),
            ],
            options={
                'verbose_name': 'Куратор',
                'verbose_name_plural': 'Кураторы',
            },
        ),
    ]
